---
- name: Check {{ path }} status
  stat:
    path: "{{ path }}"
  register: res
  with_items:
    - "{{ items_to_check }}"
- name: blockinfile create {{ create }} file {{ path_block }}
  blockinfile:
    path: "{{ path_block }}"
    create: "{{ create }}"
    mode: '{{ mode }}'
    block: "{{ block }}"
  with_items:
    - "{{ res.results }}"
  when: not item.stat.exists
